name = "SafeByteCalculators"
uuid = "88ce4d4d-ee2f-4b4a-abd3-cbc3580a88f7"
authors = ["Mark Kittisopikul <kittisopikulm@janelia.hhmi.org> and contributors"]
version = "0.1.0"

[deps]
ArrayAllocators = "c9d4266f-a5cb-439d-837c-c97b191379f5"
SaferIntegers = "88634af6-177f-5301-88b8-7819386cfa38"

[compat]
SaferIntegers = "3"
ArrayAllocators = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
